[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1

[[main]]
  identifier = "talks"
  name = "talks"
  url = "talks"
  weight = 2

[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 3


[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 4